#!/bin/bash
set -euo pipefail

VERSION=${1:-"v1.0.0"}
REPO_URL="${SUB2BALANCE_REPO_URL:-https://github.com/asdwsxzc123/sub2balance}"
SERVICE_NAME="sub2balance"

echo "🚀 Deploying Sub2Balance ${VERSION}"
echo ""

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "$ARCH" in
    x86_64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) echo "❌ Unsupported architecture: $ARCH"; exit 1 ;;
esac

BINARY_NAME="sub2balance-${OS}-${ARCH}"
ARCHIVE_NAME="${BINARY_NAME}.tar.gz"
[ "$OS" = "windows" ] && ARCHIVE_NAME="${BINARY_NAME}.zip"

echo "📦 Platform: ${OS}-${ARCH}"
echo "📥 Downloading ${ARCHIVE_NAME}..."

DOWNLOAD_URL="${REPO_URL}/releases/download/${VERSION}/${ARCHIVE_NAME}"
if ! curl -fL -o "${ARCHIVE_NAME}" "${DOWNLOAD_URL}"; then
    echo "❌ Failed to download ${DOWNLOAD_URL}"
    echo "   Check that release ${VERSION} exists at ${REPO_URL}/releases"
    exit 1
fi

echo "📂 Extracting..."
if [ "$OS" = "windows" ]; then
    unzip -q "${ARCHIVE_NAME}"
else
    tar xzf "${ARCHIVE_NAME}"
fi
chmod +x "${BINARY_NAME}"
rm -f "${ARCHIVE_NAME}"

# sudo wrapper: no-op when already root
if [ "$(id -u)" = "0" ]; then
    SUDO=""
else
    SUDO="sudo"
fi

# Generate a random secret without requiring openssl.
# /dev/urandom + tr keeps this portable on minimal images.
gen_secret() {
    local bytes=${1:-32}
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$bytes"
    else
        head -c "$((bytes * 2))" /dev/urandom | tr -dc 'a-f0-9' | head -c "$((bytes * 2))"
    fi
}

gen_password() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 18 | tr -d '/+=' | head -c 20
    else
        head -c 64 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 20
    fi
}

GENERATED_CREDS=false
if [ ! -f .env ]; then
    JWT_SECRET=$(gen_secret 32)
    ADMIN_EMAIL="admin@$(hostname -f 2>/dev/null || hostname)"
    ADMIN_PASSWORD=$(gen_password)
    cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
JWT_SECRET=${JWT_SECRET}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
    chmod 600 .env
    GENERATED_CREDS=true
    echo "📝 Generated .env with random JWT_SECRET and admin password"
fi

if [ ! -f config.yaml ] && [ -f config.yaml.example ]; then
    cp config.yaml.example config.yaml
    echo "📝 Created config.yaml from example"
fi

# Install + start systemd unit automatically (Linux only).
if [ "$OS" = "linux" ] && command -v systemctl >/dev/null 2>&1; then
    WORKDIR=$(pwd)
    RUN_USER=${SUDO_USER:-$(id -un)}

    $SUDO tee "/etc/systemd/system/${SERVICE_NAME}.service" > /dev/null <<EOF
[Unit]
Description=Sub2Balance Service
After=network.target

[Service]
Type=simple
User=${RUN_USER}
WorkingDirectory=${WORKDIR}
EnvironmentFile=${WORKDIR}/.env
ExecStart=${WORKDIR}/${BINARY_NAME}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    $SUDO systemctl daemon-reload
    $SUDO systemctl enable "${SERVICE_NAME}" >/dev/null 2>&1 || true
    $SUDO systemctl restart "${SERVICE_NAME}"

    sleep 2
    if $SUDO systemctl is-active --quiet "${SERVICE_NAME}"; then
        echo "✅ Service ${SERVICE_NAME} is running"
    else
        echo "⚠️  Service failed to start — recent logs:"
        $SUDO journalctl -u "${SERVICE_NAME}" -n 30 --no-pager || true
        exit 1
    fi
fi

echo ""
echo "✅ Deployment complete!"
echo ""
echo "Access: http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo localhost):8089"

if [ "$GENERATED_CREDS" = true ]; then
    echo ""
    echo "🔐 Initial admin credentials (save now — not shown again):"
    echo "   Email:    ${ADMIN_EMAIL}"
    echo "   Password: ${ADMIN_PASSWORD}"
    echo ""
    echo "   Full .env is at: $(pwd)/.env (chmod 600)"
fi

echo ""
echo "Next: log in, change the password, then configure Sub2API at /admin/settings"
echo "Logs:  ${SUDO:+sudo }journalctl -u ${SERVICE_NAME} -f"
